module.exports = {
  extends: ["stylelint-config-standard-scss", "stylelint-config-prettier-scss"],
  rules: {
    "selector-class-pattern": null,
    "keyframes-name-pattern": null,
    "color-function-notation": null,
    "color-function-alias-notation": null,
    "alpha-value-notation": null,
    "color-hex-length": null,
    "property-no-vendor-prefix": null,
    "media-feature-range-notation": null,
    "no-empty-source": null,
    "import-notation": null,
    "font-family-name-quotes": null,
    "rule-empty-line-before": null,
    "no-descending-specificity": null,
    "length-zero-no-unit": null,
    "shorthand-property-no-redundant-values": null,
    "declaration-block-no-redundant-longhand-properties": null,
  },
  ignoreFiles: ["**/node_modules/**", "**/.next/**", "**/dist/**", "**/out/**", "**/build/**"],
};
